---
- hosts: "{{ HOST }}"
  become_user: root
  become: yes
  tasks:

#  - name: Desabilitando o firewalld
#    ansible.builtin.systemd:
#      state: stopped
#      enabled: no
#      daemon_reload: yes
#      name: firewalld

  - name: Desabilitando SELinux
    selinux:
        state: disabled
      
  - name: Instalando pacotes adicionais
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - epel-release.noarch
      - net-tools
      - mlocate
      - zip
      - curl
      - telnet
      - vim
      - python3
      - python-docker-py.noarch
      - python-boto.noarch
      - python-boto3.noarch
      - unzip
      - figlet
      - cockpit
      - polkit
    become: yes

  - name: Subindo serviço do cockpit
    systemd:
      state: started
      name: cockpit
      enabled: yes

  - name: Configurando o timezone to America/Sao_Paulo
    shell: timedatectl set-timezone America/Sao_Paulo

  - name: Configurando o hostname
    shell: hostnamectl set-hostname "{{ HOSTNAME }}" 

  - name: Criando diretório para o dymotd
    file:
     path: /usr/src/scripts/
     state: directory
     mode: 0755
     owner: root
     group: root
     
  - name: Criando diretório para scripts
    file:
     path: /scripts/
     state: directory
     mode: 0755
     owner: root
     group: root

  - name: Copiando motd
    copy:  
      src: files/dymotd
      dest: /usr/src/scripts/dymotd
      owner: root
      group: root
      mode: '0777'

  - name: Inserindo dymotd no /etc/profile
    shell: echo "/usr/src/scripts/dymotd" >> /etc/profile

  - name: Atualizando o S.O.
    yum:
      name: '*'
      state: latest
    
  - name: Reboot do servidor
    reboot:
      reboot_timeout: 1800
    
