---
- name: Criando gurpo do vault 
  group:
    name: "{{ vault_group }}"
    state: present
  become: true

- name: Criando usuario do vault
  user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    system: yes
    shell: "/sbin/nologin"
    comment: "vault nologin User"
    createhome: "no"
    state: present